version: "3.8"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
  cli:
    image: mysql
    links:
      - mysql
    command: mysql -hmysql -uroot -pmysql
