version: "3.8"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - mysql-network
  cli:
    image: mysql
    networks:
      - mysql-network
    command: mysql -hmysql -uuser -ppassword db
networks:
  mysql-network:
    driver: bridge
